-- Drop and recreate destinations table
DROP TABLE IF EXISTS destinations CASCADE;

CREATE TABLE destinations (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    country TEXT NOT NULL,
    region TEXT NOT NULL,
    description TEXT,
    best_time TEXT,
    price_range TEXT,
    highlights TEXT[],
    image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert destination data will be generated by the Python script
